# Welcome to Jekyll-Plain!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Hayden Ghosh"
email: haydenghosh7@gmail.com
description: Hayden Ghosh's website.
baseurl: "" # the subpath of your site, e.g. "/blog" or "" for without any subpath
url: "http://haydenghosh.github.io" # the base hostname & protocol for your site

# Navigation section
# You need to define navigation items in "_data/nav.yml" and then enable using the following variable.
navigations: [home,posts,pages,notes,projects]

# The font-family set here will have a global effect on the site.
# For each of google fonts like Lora, Inconsolata, Source Sans Pro or Source Code Pro,
# a corresponding script is added to site header to make sure the font is available at client side.
font-family: ['Lora', serif]

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/social_networks.yml
social_accounts:
  email: "haydenghosh7@gmail.com"
  github: haydenghosh
  linkedin: haydenghosh

# Enable collections
# you can add more collection or remove collection by configuring the below variables.
# It is important that you keep 'tags' collection in order to let tag system work.
collections:
  pages:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name
  notes:
    output: true
    permalink: /:collection/:name

# Here we can define default layout for each of collections.
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM

# used this for post_excerpt at index_page
# add excerpt_separator to tell jekyll to which point the content will be shown in collection page.
excerpt_separator: <!--description-->

# set timezone
timezone: america/los_angeles

